version: "3"

services:
    vendor-app:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
            - /app/node_modules
        environment: 
            - PORT=5000
        # env_file:
        #     - ./.env
    
    mongo-vendor:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27017:27017"
        volumes: 
            - mongo-db:/data/db

volumes:
    mongo-db: